import { lazy, type ComponentType, type LazyExoticComponent, type ReactNode } from 'react';

/**
 * The live demos, and nothing else.
 *
 * This module used to hold the whole catalogue, built with
 * `import.meta.glob(..., { eager: true, query: '?raw' })` over every
 * component's source, README and sample JSON. That inlined 712 KB of text into
 * the bundle — a 756 KB chunk, 189 KB gzipped — and because the Master Data
 * sidebar renders the component tree, it was downloaded on *every* Master Data
 * page, none of which display any of it.
 *
 * The index and the text now come from `public/domain-catalogue.json` and
 * `public/domain-components/`, generated by
 * `frontend/react/scripts/build-domain-catalogue.mjs` and fetched on demand.
 * What cannot move to a static file is the demo itself: it has to be a real
 * module the bundler links, so it stays here — lazily, one chunk per component,
 * which it already was.
 */

// Lazy on purpose: a demo pulls in its whole component tree, and the gallery
// should not load ninety of them to show one.
const usageModules = import.meta.glob('./domains/*/*/usage.tsx');

/**
 * Every demo, wrapped once at module load.
 *
 * `lazy()` only wraps a loader — it fetches nothing until rendered — so
 * building all ninety-nine costs a map of closures and no network at all.
 *
 * Built here rather than on demand because producing a component type *during
 * render* is both forbidden by the compiler lint and wrong on its own terms: a
 * fresh type on each render remounts the demo, discarding whatever the reader
 * had just typed into it.
 */
const DEMOS: ReadonlyMap<string, LazyExoticComponent<ComponentType>> = new Map(
  Object.entries(usageModules).map(([path, loadUsage]) => {
    const id = path.replace('./domains/', '').replace('/usage.tsx', '');
    const name = id.split('/')[1];
    return [
      id,
      lazy(async () => {
        const module = (await loadUsage()) as Record<string, ComponentType>;
        // The usage file exports `<Name>Usage`; falling back to the first
        // export keeps a renamed export from blanking the gallery.
        const Component = module[`${name}Usage`] ?? Object.values(module)[0];
        return { default: Component };
      }),
    ];
  }),
);

/** Whether `domain/Name` has a demo to render. */
export function hasDemo(id: string): boolean {
  return DEMOS.has(id);
}

export interface ComponentDemoProps {
  /** `domain/Name`, as it appears in the catalogue. */
  id: string;
  /** Shown when the component has no usage file. */
  fallback?: ReactNode;
}

/**
 * Renders one component's demo.
 *
 * A component rather than a `demoFor(id)` accessor the caller renders itself.
 * Handing back a component type makes every call site look — to the compiler
 * lint, and to a reader — like it is creating a component during render, and
 * the analyser cannot see across the module boundary to know it is a map
 * lookup. Keeping the JSX here also means callers never learn that demos are
 * lazy modules at all, which is the part most likely to change.
 *
 * Suspense belongs to the caller: it knows what the loading state should look
 * like in its own layout.
 */
export function ComponentDemo({ id, fallback = null }: ComponentDemoProps) {
  const Demo = DEMOS.get(id);
  if (Demo === undefined) return <>{fallback}</>;
  return <Demo />;
}

/** Every `domain/Name` that has a demo. Used by tests to check for gaps. */
export function demoIds(): string[] {
  return [...DEMOS.keys()].sort();
}
