/**
 * AUTO-GENERATED by scripts/generate-screenshot-registry.js — do not edit.
 * Regenerate with: node scripts/generate-screenshot-registry.js
 */
import React from 'react';

import { AdvisoryAlertBannerUsage as agritech__AdvisoryAlertBanner } from '@ui/agritech';
import { BarcodeScannerOverlayUsage as agritech__BarcodeScannerOverlay } from '@ui/agritech';
import { CropCardUsage as agritech__CropCard } from '@ui/agritech';
import { FieldMapCardUsage as agritech__FieldMapCard } from '@ui/agritech';
import { InputOrderCardUsage as agritech__InputOrderCard } from '@ui/agritech';
import { InventoryStockRowUsage as agritech__InventoryStockRow } from '@ui/agritech';
import { MandiPriceListItemUsage as agritech__MandiPriceListItem } from '@ui/agritech';
import { PODCaptureSheetUsage as agritech__PODCaptureSheet } from '@ui/agritech';
import { RouteStopListItemUsage as agritech__RouteStopListItem } from '@ui/agritech';
import { ShipmentCardUsage as agritech__ShipmentCard } from '@ui/agritech';
import { ShipmentStatusTimelineUsage as agritech__ShipmentStatusTimeline } from '@ui/agritech';
import { SoilHealthCardUsage as agritech__SoilHealthCard } from '@ui/agritech';
import { VehicleTrackingCardUsage as agritech__VehicleTrackingCard } from '@ui/agritech';
import { WarehouseSelectorUsage as agritech__WarehouseSelector } from '@ui/agritech';
import { WeatherForecastStripUsage as agritech__WeatherForecastStrip } from '@ui/agritech';
import { AddToCartButtonUsage as ecommerce__AddToCartButton } from '@ui/ecommerce';
import { AddressPickerUsage as ecommerce__AddressPicker } from '@ui/ecommerce';
import { CartUsage as ecommerce__Cart } from '@ui/ecommerce';
import { CouponInputUsage as ecommerce__CouponInput } from '@ui/ecommerce';
import { FilterSortSheetUsage as ecommerce__FilterSortSheet } from '@ui/ecommerce';
import { FulfillmentUsage as ecommerce__Fulfillment } from '@ui/ecommerce';
import { ImageCarouselUsage as ecommerce__ImageCarousel } from '@ui/ecommerce';
import { PriceTagUsage as ecommerce__PriceTag } from '@ui/ecommerce';
import { ProductCardUsage as ecommerce__ProductCard } from '@ui/ecommerce';
import { QuantityStepperUsage as ecommerce__QuantityStepper } from '@ui/ecommerce';
import { ReviewsUsage as ecommerce__Reviews } from '@ui/ecommerce';
import { VariantSelectorUsage as ecommerce__VariantSelector } from '@ui/ecommerce';
import { AchievementsUsage as education__Achievements } from '@ui/education';
import { AssignmentSubmissionCardUsage as education__AssignmentSubmissionCard } from '@ui/education';
import { CourseCardUsage as education__CourseCard } from '@ui/education';
import { DiscussionThreadItemUsage as education__DiscussionThreadItem } from '@ui/education';
import { FlashCardUsage as education__FlashCard } from '@ui/education';
import { LeaderboardRowUsage as education__LeaderboardRow } from '@ui/education';
import { LessonListItemUsage as education__LessonListItem } from '@ui/education';
import { LiveClassBannerUsage as education__LiveClassBanner } from '@ui/education';
import { NoteTakerSheetUsage as education__NoteTakerSheet } from '@ui/education';
import { ProgressUsage as education__Progress } from '@ui/education';
import { QuizQuestionCardUsage as education__QuizQuestionCard } from '@ui/education';
import { QuizResultCardUsage as education__QuizResultCard } from '@ui/education';
import { VideoPlayerControlsUsage as education__VideoPlayerControls } from '@ui/education';
import { ApprovalRequestCardUsage as enterprise__ApprovalRequestCard } from '@ui/enterprise';
import { AuditLogRowUsage as enterprise__AuditLogRow } from '@ui/enterprise';
import { DashboardChartCardUsage as enterprise__DashboardChartCard } from '@ui/enterprise';
import { DataTableWrapperUsage as enterprise__DataTableWrapper } from '@ui/enterprise';
import { ExportSheetUsage as enterprise__ExportSheet } from '@ui/enterprise';
import { FileAttachmentItemUsage as enterprise__FileAttachmentItem } from '@ui/enterprise';
import { FilterToolbarUsage as enterprise__FilterToolbar } from '@ui/enterprise';
import { KPIStatCardUsage as enterprise__KPIStatCard } from '@ui/enterprise';
import { KanbanUsage as enterprise__Kanban } from '@ui/enterprise';
import { MultiStepFormWizardUsage as enterprise__MultiStepFormWizard } from '@ui/enterprise';
import { NotificationListItemUsage as enterprise__NotificationListItem } from '@ui/enterprise';
import { TaskListItemUsage as enterprise__TaskListItem } from '@ui/enterprise';
import { TeamMemberUsage as enterprise__TeamMember } from '@ui/enterprise';
import { TimelineActivityFeedUsage as enterprise__TimelineActivityFeed } from '@ui/enterprise';
import { AmountKeypadUsage as fintech__AmountKeypad } from '@ui/fintech';
import { BalanceCardUsage as fintech__BalanceCard } from '@ui/fintech';
import { CardVisualUsage as fintech__CardVisual } from '@ui/fintech';
import { EMICalculatorUsage as fintech__EMICalculator } from '@ui/fintech';
import { KYCUploaderUsage as fintech__KYCUploader } from '@ui/fintech';
import { PayeeSelectorUsage as fintech__PayeeSelector } from '@ui/fintech';
import { PaymentMethodSelectorUsage as fintech__PaymentMethodSelector } from '@ui/fintech';
import { PinPadUsage as fintech__PinPad } from '@ui/fintech';
import { SpendingCategoryChartUsage as fintech__SpendingCategoryChart } from '@ui/fintech';
import { StatementFilterSheetUsage as fintech__StatementFilterSheet } from '@ui/fintech';
import { TransactionListItemUsage as fintech__TransactionListItem } from '@ui/fintech';
import { TransactionStatusSheetUsage as fintech__TransactionStatusSheet } from '@ui/fintech';
import { ActivityRingsUsage as fitness__ActivityRings } from '@ui/fitness';
import { ExerciseListItemUsage as fitness__ExerciseListItem } from '@ui/fitness';
import { HabitCheckRowUsage as fitness__HabitCheckRow } from '@ui/fitness';
import { MealCardUsage as fitness__MealCard } from '@ui/fitness';
import { MeditationPlayerCardUsage as fitness__MeditationPlayerCard } from '@ui/fitness';
import { PersonalRecordAndStreakUsage as fitness__PersonalRecordAndStreak } from '@ui/fitness';
import { RestTimerCircleUsage as fitness__RestTimerCircle } from '@ui/fitness';
import { SleepSummaryCardUsage as fitness__SleepSummaryCard } from '@ui/fitness';
import { WaterIntakeTrackerUsage as fitness__WaterIntakeTracker } from '@ui/fitness';
import { WeightLogChartUsage as fitness__WeightLogChart } from '@ui/fitness';
import { WorkoutCardUsage as fitness__WorkoutCard } from '@ui/fitness';
import { WorkoutPlanTimelineUsage as fitness__WorkoutPlanTimeline } from '@ui/fitness';
import { AchievementUsage as gaming__Achievement } from '@ui/gaming';
import { DailyRewardUsage as gaming__DailyReward } from '@ui/gaming';
import { GameCardUsage as gaming__GameCard } from '@ui/gaming';
import { GameControlsOverlayUsage as gaming__GameControlsOverlay } from '@ui/gaming';
import { InAppPurchaseCardUsage as gaming__InAppPurchaseCard } from '@ui/gaming';
import { LeaderboardUsage as gaming__Leaderboard } from '@ui/gaming';
import { MatchmakingDialogUsage as gaming__MatchmakingDialog } from '@ui/gaming';
import { PlayerProfileCardUsage as gaming__PlayerProfileCard } from '@ui/gaming';
import { ResourcePillUsage as gaming__ResourcePill } from '@ui/gaming';
import { ScoreAndTimerUsage as gaming__ScoreAndTimer } from '@ui/gaming';
import { SpinWheelWidgetUsage as gaming__SpinWheelWidget } from '@ui/gaming';
import { TournamentCardUsage as gaming__TournamentCard } from '@ui/gaming';
import { AppointmentCardUsage as healthcare__AppointmentCard } from '@ui/healthcare';
import { AppointmentSlotGridUsage as healthcare__AppointmentSlotGrid } from '@ui/healthcare';
import { BMICalculatorCardUsage as healthcare__BMICalculatorCard } from '@ui/healthcare';
import { ChatBubbleUsage as healthcare__ChatBubble } from '@ui/healthcare';
import { ConsentDialogUsage as healthcare__ConsentDialog } from '@ui/healthcare';
import { DoctorCardUsage as healthcare__DoctorCard } from '@ui/healthcare';
import { EmergencyContactCardUsage as healthcare__EmergencyContactCard } from '@ui/healthcare';
import { HealthDocumentsUsage as healthcare__HealthDocuments } from '@ui/healthcare';
import { HealthQuestionnaireFormUsage as healthcare__HealthQuestionnaireForm } from '@ui/healthcare';
import { MedicationReminderItemUsage as healthcare__MedicationReminderItem } from '@ui/healthcare';
import { SymptomSelectorUsage as healthcare__SymptomSelector } from '@ui/healthcare';
import { VideoCallControlsBarUsage as healthcare__VideoCallControlsBar } from '@ui/healthcare';
import { VitalsCardUsage as healthcare__VitalsCard } from '@ui/healthcare';
import { AutomationRuleCardUsage as iot__AutomationRuleCard } from '@ui/iot';
import { ColorPickerUsage as iot__ColorPicker } from '@ui/iot';
import { DeviceCardUsage as iot__DeviceCard } from '@ui/iot';
import { DeviceHealthUsage as iot__DeviceHealth } from '@ui/iot';
import { DevicePairingWizardUsage as iot__DevicePairingWizard } from '@ui/iot';
import { DeviceToggleTileUsage as iot__DeviceToggleTile } from '@ui/iot';
import { FirmwareUpdateCardUsage as iot__FirmwareUpdateCard } from '@ui/iot';
import { RoomTabsUsage as iot__RoomTabs } from '@ui/iot';
import { SceneCardUsage as iot__SceneCard } from '@ui/iot';
import { ScheduleTimerRowUsage as iot__ScheduleTimerRow } from '@ui/iot';
import { SensorReadingCardUsage as iot__SensorReadingCard } from '@ui/iot';
import { SliderControlUsage as iot__SliderControl } from '@ui/iot';
import { ThermostatDialUsage as iot__ThermostatDial } from '@ui/iot';
import { CastCrewStripUsage as media__CastCrewStrip } from '@ui/media';
import { ContentCarouselUsage as media__ContentCarousel } from '@ui/media';
import { ContentPosterCardUsage as media__ContentPosterCard } from '@ui/media';
import { ContinueWatchingCardUsage as media__ContinueWatchingCard } from '@ui/media';
import { DownloadStatusButtonUsage as media__DownloadStatusButton } from '@ui/media';
import { EpisodeListItemUsage as media__EpisodeListItem } from '@ui/media';
import { HeroBannerUsage as media__HeroBanner } from '@ui/media';
import { MiniPlayerBarUsage as media__MiniPlayerBar } from '@ui/media';
import { PlayerControlsOverlayUsage as media__PlayerControlsOverlay } from '@ui/media';
import { SeasonSelectorUsage as media__SeasonSelector } from '@ui/media';
import { SubscriptionPlanCardUsage as media__SubscriptionPlanCard } from '@ui/media';
import { WatchlistAndRatingUsage as media__WatchlistAndRating } from '@ui/media';
import { AgentContactCardUsage as realestate__AgentContactCard } from '@ui/realestate';
import { AmenityGridUsage as realestate__AmenityGrid } from '@ui/realestate';
import { ComparePropertiesTableUsage as realestate__ComparePropertiesTable } from '@ui/realestate';
import { DocumentChecklistItemUsage as realestate__DocumentChecklistItem } from '@ui/realestate';
import { EMICalculatorCardUsage as realestate__EMICalculatorCard } from '@ui/realestate';
import { LocalityInsightsCardUsage as realestate__LocalityInsightsCard } from '@ui/realestate';
import { PropertyCardUsage as realestate__PropertyCard } from '@ui/realestate';
import { PropertyFilterSheetUsage as realestate__PropertyFilterSheet } from '@ui/realestate';
import { PropertyMediaUsage as realestate__PropertyMedia } from '@ui/realestate';
import { PropertyStatusChipUsage as realestate__PropertyStatusChip } from '@ui/realestate';
import { SavedSearchAndTrendUsage as realestate__SavedSearchAndTrend } from '@ui/realestate';
import { SiteVisitSchedulerSheetUsage as realestate__SiteVisitSchedulerSheet } from '@ui/realestate';
import { ChatInputBarUsage as social__ChatInputBar } from '@ui/social';
import { CommentsUsage as social__Comments } from '@ui/social';
import { ConversationListItemUsage as social__ConversationListItem } from '@ui/social';
import { FollowButtonUsage as social__FollowButton } from '@ui/social';
import { MediaGridViewerUsage as social__MediaGridViewer } from '@ui/social';
import { MentionTextInputUsage as social__MentionTextInput } from '@ui/social';
import { MessageBubbleUsage as social__MessageBubble } from '@ui/social';
import { MessageStatusUsage as social__MessageStatus } from '@ui/social';
import { PostCardUsage as social__PostCard } from '@ui/social';
import { ReactionBarUsage as social__ReactionBar } from '@ui/social';
import { ReportBlockSheetUsage as social__ReportBlockSheet } from '@ui/social';
import { StoriesUsage as social__Stories } from '@ui/social';
import { UserProfileHeaderUsage as social__UserProfileHeader } from '@ui/social';
import { DriverCardUsage as transportation__DriverCard } from '@ui/transportation';
import { FareEstimateCardUsage as transportation__FareEstimateCard } from '@ui/transportation';
import { LocationSearchSheetUsage as transportation__LocationSearchSheet } from '@ui/transportation';
import { MapMarkerCalloutUsage as transportation__MapMarkerCallout } from '@ui/transportation';
import { OTPDisplayCardUsage as transportation__OTPDisplayCard } from '@ui/transportation';
import { RideHistoryListItemUsage as transportation__RideHistoryListItem } from '@ui/transportation';
import { RideStatusBottomSheetUsage as transportation__RideStatusBottomSheet } from '@ui/transportation';
import { RideTypeSelectorUsage as transportation__RideTypeSelector } from '@ui/transportation';
import { SOSButtonUsage as transportation__SOSButton } from '@ui/transportation';
import { SavedPlaceItemUsage as transportation__SavedPlaceItem } from '@ui/transportation';
import { ScheduleRideSheetUsage as transportation__ScheduleRideSheet } from '@ui/transportation';
import { TipSelectorUsage as transportation__TipSelector } from '@ui/transportation';
import { TripSummaryCardUsage as transportation__TripSummaryCard } from '@ui/transportation';
import { AmenityIconGridUsage as travel__AmenityIconGrid } from '@ui/travel';
import { BookingTicketCardUsage as travel__BookingTicketCard } from '@ui/travel';
import { CancellationPolicyCardUsage as travel__CancellationPolicyCard } from '@ui/travel';
import { FareBreakdownAccordionUsage as travel__FareBreakdownAccordion } from '@ui/travel';
import { FlightResultCardUsage as travel__FlightResultCard } from '@ui/travel';
import { GuestRoomSelectorUsage as travel__GuestRoomSelector } from '@ui/travel';
import { HotelCardUsage as travel__HotelCard } from '@ui/travel';
import { ItineraryTimelineUsage as travel__ItineraryTimeline } from '@ui/travel';
import { PriceCalendarStripUsage as travel__PriceCalendarStrip } from '@ui/travel';
import { ReviewSummaryCardUsage as travel__ReviewSummaryCard } from '@ui/travel';
import { RoomTypeCardUsage as travel__RoomTypeCard } from '@ui/travel';
import { SearchWidgetUsage as travel__SearchWidget } from '@ui/travel';
import { TravellerDetailsFormUsage as travel__TravellerDetailsForm } from '@ui/travel';

export const SCREENSHOT_REGISTRY: Record<string, React.ComponentType> = {
  'agritech-AdvisoryAlertBanner': agritech__AdvisoryAlertBanner,
  'agritech-BarcodeScannerOverlay': agritech__BarcodeScannerOverlay,
  'agritech-CropCard': agritech__CropCard,
  'agritech-FieldMapCard': agritech__FieldMapCard,
  'agritech-InputOrderCard': agritech__InputOrderCard,
  'agritech-InventoryStockRow': agritech__InventoryStockRow,
  'agritech-MandiPriceListItem': agritech__MandiPriceListItem,
  'agritech-PODCaptureSheet': agritech__PODCaptureSheet,
  'agritech-RouteStopListItem': agritech__RouteStopListItem,
  'agritech-ShipmentCard': agritech__ShipmentCard,
  'agritech-ShipmentStatusTimeline': agritech__ShipmentStatusTimeline,
  'agritech-SoilHealthCard': agritech__SoilHealthCard,
  'agritech-VehicleTrackingCard': agritech__VehicleTrackingCard,
  'agritech-WarehouseSelector': agritech__WarehouseSelector,
  'agritech-WeatherForecastStrip': agritech__WeatherForecastStrip,
  'ecommerce-AddToCartButton': ecommerce__AddToCartButton,
  'ecommerce-AddressPicker': ecommerce__AddressPicker,
  'ecommerce-Cart': ecommerce__Cart,
  'ecommerce-CouponInput': ecommerce__CouponInput,
  'ecommerce-FilterSortSheet': ecommerce__FilterSortSheet,
  'ecommerce-Fulfillment': ecommerce__Fulfillment,
  'ecommerce-ImageCarousel': ecommerce__ImageCarousel,
  'ecommerce-PriceTag': ecommerce__PriceTag,
  'ecommerce-ProductCard': ecommerce__ProductCard,
  'ecommerce-QuantityStepper': ecommerce__QuantityStepper,
  'ecommerce-Reviews': ecommerce__Reviews,
  'ecommerce-VariantSelector': ecommerce__VariantSelector,
  'education-Achievements': education__Achievements,
  'education-AssignmentSubmissionCard': education__AssignmentSubmissionCard,
  'education-CourseCard': education__CourseCard,
  'education-DiscussionThreadItem': education__DiscussionThreadItem,
  'education-FlashCard': education__FlashCard,
  'education-LeaderboardRow': education__LeaderboardRow,
  'education-LessonListItem': education__LessonListItem,
  'education-LiveClassBanner': education__LiveClassBanner,
  'education-NoteTakerSheet': education__NoteTakerSheet,
  'education-Progress': education__Progress,
  'education-QuizQuestionCard': education__QuizQuestionCard,
  'education-QuizResultCard': education__QuizResultCard,
  'education-VideoPlayerControls': education__VideoPlayerControls,
  'enterprise-ApprovalRequestCard': enterprise__ApprovalRequestCard,
  'enterprise-AuditLogRow': enterprise__AuditLogRow,
  'enterprise-DashboardChartCard': enterprise__DashboardChartCard,
  'enterprise-DataTableWrapper': enterprise__DataTableWrapper,
  'enterprise-ExportSheet': enterprise__ExportSheet,
  'enterprise-FileAttachmentItem': enterprise__FileAttachmentItem,
  'enterprise-FilterToolbar': enterprise__FilterToolbar,
  'enterprise-KPIStatCard': enterprise__KPIStatCard,
  'enterprise-Kanban': enterprise__Kanban,
  'enterprise-MultiStepFormWizard': enterprise__MultiStepFormWizard,
  'enterprise-NotificationListItem': enterprise__NotificationListItem,
  'enterprise-TaskListItem': enterprise__TaskListItem,
  'enterprise-TeamMember': enterprise__TeamMember,
  'enterprise-TimelineActivityFeed': enterprise__TimelineActivityFeed,
  'fintech-AmountKeypad': fintech__AmountKeypad,
  'fintech-BalanceCard': fintech__BalanceCard,
  'fintech-CardVisual': fintech__CardVisual,
  'fintech-EMICalculator': fintech__EMICalculator,
  'fintech-KYCUploader': fintech__KYCUploader,
  'fintech-PayeeSelector': fintech__PayeeSelector,
  'fintech-PaymentMethodSelector': fintech__PaymentMethodSelector,
  'fintech-PinPad': fintech__PinPad,
  'fintech-SpendingCategoryChart': fintech__SpendingCategoryChart,
  'fintech-StatementFilterSheet': fintech__StatementFilterSheet,
  'fintech-TransactionListItem': fintech__TransactionListItem,
  'fintech-TransactionStatusSheet': fintech__TransactionStatusSheet,
  'fitness-ActivityRings': fitness__ActivityRings,
  'fitness-ExerciseListItem': fitness__ExerciseListItem,
  'fitness-HabitCheckRow': fitness__HabitCheckRow,
  'fitness-MealCard': fitness__MealCard,
  'fitness-MeditationPlayerCard': fitness__MeditationPlayerCard,
  'fitness-PersonalRecordAndStreak': fitness__PersonalRecordAndStreak,
  'fitness-RestTimerCircle': fitness__RestTimerCircle,
  'fitness-SleepSummaryCard': fitness__SleepSummaryCard,
  'fitness-WaterIntakeTracker': fitness__WaterIntakeTracker,
  'fitness-WeightLogChart': fitness__WeightLogChart,
  'fitness-WorkoutCard': fitness__WorkoutCard,
  'fitness-WorkoutPlanTimeline': fitness__WorkoutPlanTimeline,
  'gaming-Achievement': gaming__Achievement,
  'gaming-DailyReward': gaming__DailyReward,
  'gaming-GameCard': gaming__GameCard,
  'gaming-GameControlsOverlay': gaming__GameControlsOverlay,
  'gaming-InAppPurchaseCard': gaming__InAppPurchaseCard,
  'gaming-Leaderboard': gaming__Leaderboard,
  'gaming-MatchmakingDialog': gaming__MatchmakingDialog,
  'gaming-PlayerProfileCard': gaming__PlayerProfileCard,
  'gaming-ResourcePill': gaming__ResourcePill,
  'gaming-ScoreAndTimer': gaming__ScoreAndTimer,
  'gaming-SpinWheelWidget': gaming__SpinWheelWidget,
  'gaming-TournamentCard': gaming__TournamentCard,
  'healthcare-AppointmentCard': healthcare__AppointmentCard,
  'healthcare-AppointmentSlotGrid': healthcare__AppointmentSlotGrid,
  'healthcare-BMICalculatorCard': healthcare__BMICalculatorCard,
  'healthcare-ChatBubble': healthcare__ChatBubble,
  'healthcare-ConsentDialog': healthcare__ConsentDialog,
  'healthcare-DoctorCard': healthcare__DoctorCard,
  'healthcare-EmergencyContactCard': healthcare__EmergencyContactCard,
  'healthcare-HealthDocuments': healthcare__HealthDocuments,
  'healthcare-HealthQuestionnaireForm': healthcare__HealthQuestionnaireForm,
  'healthcare-MedicationReminderItem': healthcare__MedicationReminderItem,
  'healthcare-SymptomSelector': healthcare__SymptomSelector,
  'healthcare-VideoCallControlsBar': healthcare__VideoCallControlsBar,
  'healthcare-VitalsCard': healthcare__VitalsCard,
  'iot-AutomationRuleCard': iot__AutomationRuleCard,
  'iot-ColorPicker': iot__ColorPicker,
  'iot-DeviceCard': iot__DeviceCard,
  'iot-DeviceHealth': iot__DeviceHealth,
  'iot-DevicePairingWizard': iot__DevicePairingWizard,
  'iot-DeviceToggleTile': iot__DeviceToggleTile,
  'iot-FirmwareUpdateCard': iot__FirmwareUpdateCard,
  'iot-RoomTabs': iot__RoomTabs,
  'iot-SceneCard': iot__SceneCard,
  'iot-ScheduleTimerRow': iot__ScheduleTimerRow,
  'iot-SensorReadingCard': iot__SensorReadingCard,
  'iot-SliderControl': iot__SliderControl,
  'iot-ThermostatDial': iot__ThermostatDial,
  'media-CastCrewStrip': media__CastCrewStrip,
  'media-ContentCarousel': media__ContentCarousel,
  'media-ContentPosterCard': media__ContentPosterCard,
  'media-ContinueWatchingCard': media__ContinueWatchingCard,
  'media-DownloadStatusButton': media__DownloadStatusButton,
  'media-EpisodeListItem': media__EpisodeListItem,
  'media-HeroBanner': media__HeroBanner,
  'media-MiniPlayerBar': media__MiniPlayerBar,
  'media-PlayerControlsOverlay': media__PlayerControlsOverlay,
  'media-SeasonSelector': media__SeasonSelector,
  'media-SubscriptionPlanCard': media__SubscriptionPlanCard,
  'media-WatchlistAndRating': media__WatchlistAndRating,
  'realestate-AgentContactCard': realestate__AgentContactCard,
  'realestate-AmenityGrid': realestate__AmenityGrid,
  'realestate-ComparePropertiesTable': realestate__ComparePropertiesTable,
  'realestate-DocumentChecklistItem': realestate__DocumentChecklistItem,
  'realestate-EMICalculatorCard': realestate__EMICalculatorCard,
  'realestate-LocalityInsightsCard': realestate__LocalityInsightsCard,
  'realestate-PropertyCard': realestate__PropertyCard,
  'realestate-PropertyFilterSheet': realestate__PropertyFilterSheet,
  'realestate-PropertyMedia': realestate__PropertyMedia,
  'realestate-PropertyStatusChip': realestate__PropertyStatusChip,
  'realestate-SavedSearchAndTrend': realestate__SavedSearchAndTrend,
  'realestate-SiteVisitSchedulerSheet': realestate__SiteVisitSchedulerSheet,
  'social-ChatInputBar': social__ChatInputBar,
  'social-Comments': social__Comments,
  'social-ConversationListItem': social__ConversationListItem,
  'social-FollowButton': social__FollowButton,
  'social-MediaGridViewer': social__MediaGridViewer,
  'social-MentionTextInput': social__MentionTextInput,
  'social-MessageBubble': social__MessageBubble,
  'social-MessageStatus': social__MessageStatus,
  'social-PostCard': social__PostCard,
  'social-ReactionBar': social__ReactionBar,
  'social-ReportBlockSheet': social__ReportBlockSheet,
  'social-Stories': social__Stories,
  'social-UserProfileHeader': social__UserProfileHeader,
  'transportation-DriverCard': transportation__DriverCard,
  'transportation-FareEstimateCard': transportation__FareEstimateCard,
  'transportation-LocationSearchSheet': transportation__LocationSearchSheet,
  'transportation-MapMarkerCallout': transportation__MapMarkerCallout,
  'transportation-OTPDisplayCard': transportation__OTPDisplayCard,
  'transportation-RideHistoryListItem': transportation__RideHistoryListItem,
  'transportation-RideStatusBottomSheet': transportation__RideStatusBottomSheet,
  'transportation-RideTypeSelector': transportation__RideTypeSelector,
  'transportation-SOSButton': transportation__SOSButton,
  'transportation-SavedPlaceItem': transportation__SavedPlaceItem,
  'transportation-ScheduleRideSheet': transportation__ScheduleRideSheet,
  'transportation-TipSelector': transportation__TipSelector,
  'transportation-TripSummaryCard': transportation__TripSummaryCard,
  'travel-AmenityIconGrid': travel__AmenityIconGrid,
  'travel-BookingTicketCard': travel__BookingTicketCard,
  'travel-CancellationPolicyCard': travel__CancellationPolicyCard,
  'travel-FareBreakdownAccordion': travel__FareBreakdownAccordion,
  'travel-FlightResultCard': travel__FlightResultCard,
  'travel-GuestRoomSelector': travel__GuestRoomSelector,
  'travel-HotelCard': travel__HotelCard,
  'travel-ItineraryTimeline': travel__ItineraryTimeline,
  'travel-PriceCalendarStrip': travel__PriceCalendarStrip,
  'travel-ReviewSummaryCard': travel__ReviewSummaryCard,
  'travel-RoomTypeCard': travel__RoomTypeCard,
  'travel-SearchWidget': travel__SearchWidget,
  'travel-TravellerDetailsForm': travel__TravellerDetailsForm,
};

export type ScreenshotKey = keyof typeof SCREENSHOT_REGISTRY;
