/**
 * Layer 1 — Design tokens.
 *
 * The raw values live in `design-tokens/*.tokens.json` so a brand can be swapped
 * (or generated by Style Dictionary) without touching a single component. This
 * module is the only place allowed to read that JSON; everything else consumes
 * the typed `AppTheme` produced in `theme.ts`.
 */
import raw from '../../design-tokens/base.tokens.json';

export type ColorTokenName = keyof typeof raw.color.light;
export type ColorScheme = 'light' | 'dark';

export type SpacingToken = keyof typeof raw.spacing;
export type RadiusToken = keyof typeof raw.radii;
export type DurationToken = keyof typeof raw.motion.duration;
export type EasingToken = keyof typeof raw.motion.easing;
export type SpringToken = keyof typeof raw.motion.spring;
export type ElevationToken = keyof typeof raw.elevation;
export type ControlSize = keyof typeof raw.sizing.control;

export type BezierTuple = readonly [number, number, number, number];

export interface SpringConfigToken {
  damping: number;
  stiffness: number;
  mass: number;
}

export interface DesignTokens {
  brand: string;
  color: Record<ColorScheme, Record<ColorTokenName, string>>;
  spacing: Record<SpacingToken, number>;
  radii: Record<RadiusToken, number>;
  sizing: {
    control: Record<ControlSize, number>;
    icon: Record<ControlSize, number>;
    avatar: Record<ControlSize, number>;
    hitSlop: number;
    minTouchTarget: number;
  };
  typography: {
    label: Record<ControlSize, number>;
    body: Record<ControlSize, number>;
    title: Record<ControlSize, number>;
  };
  motion: {
    duration: Record<DurationToken, number>;
    easing: Record<EasingToken, BezierTuple>;
    spring: Record<SpringToken, SpringConfigToken>;
    stagger: { item: number; max: number };
  };
  elevation: Record<ElevationToken, number>;
  opacity: { disabled: number; muted: number; backdrop: number; pressed: number };
}

export const tokens = raw as unknown as DesignTokens;
