"""Step 22 - Create Pull Request.

Component: PLUGIN (GitHub)      Category: VCS Publication

The PR body is the audit package: it links every artifact the pipeline produced,
so a human reviewer at step 24 can trace any line of code back through the TDD,
the spec, the impact manifest, the BRD, and finally the Jira story - without
leaving the PR.

The PR opens as a draft. It becomes a merge candidate only after gate 24.

Which repository it opens against is `plugins.vcs.repo`, and it need not be the
repository the pipeline edited: a deployment can edit a working copy and propose
the change to a different, canonical repo. See `docs/12-pull-request-target.md`.
"""

from __future__ import annotations

import re
from typing import Any

from ..core.component import Plugin
from ..core.envelope import Envelope
from ..core.errors import PolicyViolation, VcsError
from ..core.identity import author_for, can_publish
from ..core.parts import structured
from ..plugins.factory import build_plugin


def slugify(text: str, limit: int = 40) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:limit]


class PullRequestCreation(Plugin):
    step = 22
    name = "pull_request_creation"
    category = "VCS Publication"
    consumes = ["BrdV1", "TechnicalDesignV1", "CodeChangesetV1", "TestReportV1", "AiReviewV1"]
    produces = ["22_pull_request__{job}__v{v}.json"]
    accepts = ["application/json"]

    def handle(self, env: Envelope, ctx: Any) -> Envelope:
        vcs = build_plugin(ctx.cfg, "vcs", ctx)
        brd = ctx.recall("BrdV1") or {}
        title = f"{ctx.jira_id}: {brd.get('title', 'change')}"
        branch = vcs.branch_name(
            ctx.jira_id, slugify(brd.get("title", "change")), ctx.job_id
        )

        published = self._publish(ctx, vcs, branch, title)
        pr = vcs.open_pull_request(title=title, body=self._body(ctx, brd), head=branch)
        pr["commit"] = published.get("sha", "")
        ctx.remember("PullRequestV1", pr)
        ctx.artifacts.write(self.step, "pull_request", pr, ext="json")
        return env.reply(self.ref(), [structured("PullRequestV1", pr)])

    # ------------------------------------------------------------------ #
    def _publish(self, ctx: Any, vcs: Any, branch: str, title: str) -> dict:
        """Commit and push the run's work before asking for a pull request.

        Nothing else in the pipeline writes to git: steps 12-21 edit the working
        copy and stop there. Without this, `open_pull_request` asks GitHub to
        open a PR from a branch that was never pushed, and the run ends on a 422
        about a head that does not exist.
        """
        changeset = ctx.recall("CodeChangesetV1") or {}
        paths = self._changed_paths(changeset)
        self._assert_inside_write_scope(ctx, paths)

        published = vcs.publish_branch(
            ctx.workspace,
            branch=branch,
            paths=paths,
            message=f"{title}\n\nJob: {ctx.job_id}\nGenerated by CodeGen Core.",
            # Only a run that will actually author a commit needs an author. A
            # dry-run produces no commit to attribute, which is what keeps the
            # offline pipeline runnable with no arguments.
            author=author_for(ctx) if can_publish(ctx.cfg) else ("", ""),
        )
        if published.get("sha"):
            # The field has existed on CodeChangesetV1 since it was written and
            # has always been empty; this is what fills it.
            changeset["commits"] = [published["sha"]]
            ctx.remember("CodeChangesetV1", changeset)
        ctx.journal.append_event(
            "branch_published",
            branch=branch,
            sha=published.get("sha", ""),
            repo=published.get("repo", ""),
            files=len(paths),
            dry_run=published.get("dry_run", False),
        )
        return published

    @staticmethod
    def _changed_paths(changeset: dict) -> list[str]:
        seen = dict.fromkeys(
            [*changeset.get("changed_files", []), *changeset.get("created_files", [])]
        )
        return [p for p in seen if p]

    def _assert_inside_write_scope(self, ctx: Any, paths: list[str]) -> None:
        """Refuse to commit anything step 09 did not authorise.

        A `cli_agent` backend with `edits_files_directly` writes to disk itself
        and bypasses GuardedFS, so the working tree can hold changes policy
        never approved. Filtering them out silently would ship a pull request
        missing part of its own change; this halts instead, naming the paths, so
        a person decides whether the manifest or the edit is wrong.
        """
        manifest = ctx.recall("ImpactManifestV1") or {}
        allowed = manifest.get("allowed_paths") or []
        if not allowed:
            return

        refused = []
        for path in paths:
            try:
                # The same check GuardedFS applies on write, re-applied here: it
                # also covers the deny globs and the migration signoff rule, so
                # a bypassed write cannot reach a commit by any of those routes.
                ctx.policy.check_path(path, allowed)
            except PolicyViolation as exc:
                refused.append(str(exc))
        if refused:
            raise PolicyViolation(
                "refusing to commit: the working tree holds changes step 09 did not "
                "authorise, which means something wrote outside GuardedFS. "
                + "; ".join(sorted(refused))
            )

    def _body(self, ctx: Any, brd: dict) -> str:
        tests = ctx.recall("TestReportV1") or {}
        coverage = tests.get("coverage", {})
        security = ctx.recall("SecurityScanV1") or {}
        coverage_report = ctx.recall("RequirementCoverageV1") or {}
        artifacts = "\n".join(
            f"- `{e['file']}` ({e['output_class']}, {e['bytes']} bytes)"
            for e in ctx.artifacts.index()
        )
        acs = "\n".join(f"- **{a['id']}** {a['text']}" for a in brd.get("acceptance_criteria", []))
        return (
            f"## {brd.get('title', '')}\n\n"
            f"**Jira:** {ctx.jira_id}\n"
            f"**Job:** `{ctx.job_id}`\n"
            f"**Profile:** `{ctx.cfg.active_profile}`\n\n"
            f"### Acceptance Criteria\n{acs or '- (none)'}\n\n"
            f"### Verification\n"
            f"- Requirement coverage: {coverage_report.get('verdict', 'n/a')} "
            f"(missing: {coverage_report.get('missing', [])})\n"
            f"- Unit tests: {tests.get('passed', 0)} passed / {tests.get('failed', 0)} failed\n"
            f"- Line coverage: {coverage.get('line_pct', 0)}% "
            f"(changed lines: {coverage.get('changed_line_pct', 0)}%)\n"
            f"- Blocking security findings: {len(security.get('blocking_findings', []))}\n"
            f"- Total model cost: ${ctx.journal.total_cost_usd()}\n\n"
            f"### Artifacts\n{artifacts}\n\n"
            "### Reviewer checklist\n"
            "- [ ] The change matches the approved BRD, and nothing more\n"
            "- [ ] Tests assert intended behaviour rather than current behaviour\n"
            "- [ ] Security findings are resolved or explicitly accepted\n"
            "- [ ] Documentation reflects the shipped implementation\n"
        )


STEP = PullRequestCreation()
